language: c
sudo: false
os:
- linux

before_install:
- sudo apt-get install -y gcc-arm-none-eabi
- sudo apt-get install -y vera++

addons:
  apt:
    update: true

script:
  - cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cortexM0.cmake
  - cd build
  - make bootSPI
  - make bootCAN
