language: c
sudo: false
os:
- linux

before_install:
- sudo apt-get install -y gcc-arm-none-eabi
- git clone https://bitbucket.org/verateam/vera.git
- cd vera
- git submodule update --init
- sed -i 's/ON/OFF/1' ./src/lua.cmake
- mkdir build
- cd build
- cmake ..
- make -j
- sudo make install

addons:
  apt:
    update: true

script:
  - cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cortexM0.cmake
  - cmake --build build --
