language: c
sudo: false
os:
- linux

before_install:
- sudo apt-get install -y gcc-arm-none-eabi
- sudo apt-get install -y vera++

addons:
  apt:
    update: true

script:
  - which arm-none-eabi-gcc

  - cmake -H. -Bbuild
  - cmake --build build --