language: c
sudo: false
os:
- linux

before_install:

  - mkdir .compiler
  - export ARM_GCC_ROOT_FOLDER=~/.compiler/
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2?revision=ca0cbf9c-9de2-491c-ac48-898b5bbc0443&la=en&hash=68760A8AE66026BCF99F05AC017A6A50C6FD832A
  - tar -jxvf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 --directory ~/.compiler

addons:
  apt:
    update: true

script:
  - cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cmake/cortexM0.cmake
  - cmake --build build --
