language: c
sudo: false
os:
- linux

before_install:
  - cd ~
  - mkdir ~/.compiler
  - export ARM_GCC_ROOT_FOLDER=~/.compiler/gcc-arm-none-eabi-10-2020-q4-major/arm-none-eabi/
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
  - tar -jxvf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 --directory ~/.compiler
  - cd /travis/sohal/stmApp

addons:
  apt:
    update: true

script:
  - cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cmake/cortexM0.cmake
  - cmake --build build --
