language: c
compiler: 
- gcc
sudo: false
os:
- linux

before_install:
- sudo apt-get install -y gcc-arm-none-eabi
- sudo apt-get install -y vera++

addons:
  apt:
    update: true

script:
- cmake -H. -Bbuild
- cmake --build build --