language: c
sudo: false
os:
- linux

before_install:
- sudo apt-get install -y gcc-arm-none-eabi
- export ARM_GCC_ROOT_FOLDER=/usr
- whereis arm-none-eabi-gcc
addons:
  apt:
    update: true

script:
  - cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cmake/cortexM0.cmake
  - cmake --build build --
